# Google Cloud Build configuration for React frontend deployment to Cloud Run
steps:
  # Build the Docker image with Firebase configuration
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/aigm-frontend:latest',
      '--build-arg', 'VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}',
      '--build-arg', 'VITE_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}',
      '--build-arg', 'VITE_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}',
      '--build-arg', 'VITE_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}',
      '--build-arg', 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg', 'VITE_FIREBASE_APP_ID=${_FIREBASE_APP_ID}',
      '--build-arg', 'VITE_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}',
      './frontend'
    ]
    id: 'build-image'

  # Push the image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA']
    id: 'push-sha-image'
    waitFor: ['build-image']

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aigm-frontend:latest']
    id: 'push-latest-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'aigm-frontend',
      '--image', 'gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '100',
      '--concurrency', '80',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production',
      '--labels', 'app=aigm-frontend,environment=production',
      '--quiet'
    ]
    id: 'deploy-cloud-run'
    waitFor: ['push-sha-image']

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'

# Timeout for entire build
timeout: '600s'

# Substitutions (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'aigm-frontend'
  # Firebase configuration - Using actual aigm-theendpoint values
  _FIREBASE_API_KEY: 'AIzaSyD1UJ7ezP27TBWEiK3itjgMu1Sjb60Ln78'
  _FIREBASE_AUTH_DOMAIN: 'aigm-theendpoint.firebaseapp.com'
  _FIREBASE_PROJECT_ID: 'aigm-theendpoint'
  _FIREBASE_STORAGE_BUCKET: 'aigm-theendpoint.firebasestorage.app'
  _FIREBASE_MESSAGING_SENDER_ID: '248133304179'
  _FIREBASE_APP_ID: '1:248133304179:web:a0a062608e56ab01968f06'
  _FIREBASE_MEASUREMENT_ID: 'G-43M2G4HWEQ'