# Google Cloud Build configuration for React frontend deployment to Cloud Run
steps:
  # Build the Docker image with Firebase configuration from Secret Manager
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
      '-c',
      'docker build -t gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA -t gcr.io/$PROJECT_ID/aigm-frontend:latest --build-arg VITE_FIREBASE_API_KEY=$$FIREBASE_API_KEY --build-arg VITE_FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN --build-arg VITE_FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID --build-arg VITE_FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID --build-arg VITE_FIREBASE_APP_ID=$$FIREBASE_APP_ID --build-arg VITE_FIREBASE_MEASUREMENT_ID=$$FIREBASE_MEASUREMENT_ID ./frontend'
    ]
    id: 'build-image'
    secretEnv: [
      'FIREBASE_API_KEY',
      'FIREBASE_AUTH_DOMAIN', 
      'FIREBASE_PROJECT_ID',
      'FIREBASE_STORAGE_BUCKET',
      'FIREBASE_MESSAGING_SENDER_ID',
      'FIREBASE_APP_ID',
      'FIREBASE_MEASUREMENT_ID'
    ]

  # Push the image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA']
    id: 'push-sha-image'
    waitFor: ['build-image']

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aigm-frontend:latest']
    id: 'push-latest-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'aigm-frontend',
      '--image', 'gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '100',
      '--concurrency', '80',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production',
      '--labels', 'app=aigm-frontend,environment=production',
      '--quiet'
    ]
    id: 'deploy-cloud-run'
    waitFor: ['push-sha-image']

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'

# Timeout for entire build
timeout: '600s'

# Available secrets from Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/firebase-api-key/versions/latest
    env: 'FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/firebase-auth-domain/versions/latest
    env: 'FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/firebase-project-id/versions/latest
    env: 'FIREBASE_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/firebase-storage-bucket/versions/latest
    env: 'FIREBASE_STORAGE_BUCKET'
  - versionName: projects/$PROJECT_ID/secrets/firebase-messaging-sender-id/versions/latest
    env: 'FIREBASE_MESSAGING_SENDER_ID'
  - versionName: projects/$PROJECT_ID/secrets/firebase-app-id/versions/latest
    env: 'FIREBASE_APP_ID'
  - versionName: projects/$PROJECT_ID/secrets/firebase-measurement-id/versions/latest
    env: 'FIREBASE_MEASUREMENT_ID'

# Substitutions (for future use)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'aigm-frontend'