# Google Cloud Build configuration for React frontend deployment to Cloud Run
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/aigm-frontend:latest',
      './frontend'
    ]
    id: 'build-image'

  # Push the image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA']
    id: 'push-sha-image'
    waitFor: ['build-image']

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aigm-frontend:latest']
    id: 'push-latest-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'aigm-frontend',
      '--image', 'gcr.io/$PROJECT_ID/aigm-frontend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '100',
      '--concurrency', '80',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production',
      '--labels', 'app=aigm-frontend,environment=production',
      '--quiet'
    ]
    id: 'deploy-cloud-run'
    waitFor: ['push-sha-image']

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'

# Timeout for entire build
timeout: '600s'

# Substitutions (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'aigm-frontend'